services:
  - type: web
    name: exam-proctor-server
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: exam-proctor-db
          property: connectionString
      - key: CLIENT_URL
        value: https://interview-proctor-system.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloudinary-cloud-name
      - key: CLOUDINARY_API_KEY
        value: your-cloudinary-api-key
      - key: CLOUDINARY_API_SECRET
        value: your-cloudinary-api-secret

databases:
  - name: exam-proctor-db
    plan: starter
